import inspect
import colorama

print(__name__)
print(inspect.ismodule(colorama))
print(inspect.ismethod(colorama))
print(inspect.isfunction(colorama))
print(inspect.isclass(colorama))
print(callable(colorama))
print(colorama.__name__)
print(colorama.__init__)
print(colorama.__doc__)
print(colorama.__dir__)
print(colorama.__version__)
print(colorama.__file__)
print(colorama.__cached__)
print(colorama.__builtins__)
print(colorama.__spec__)
print(colorama.__package__)
print(colorama)
for item in dir():
    print(item)
print(colorama)
help(colorama)
print("colorama -  це модуль він може змінювати колір тексту ")
